Keras basics

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
X = iris.data

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# class 0 -->[1,0,0]
# class 1 -->[0,1,0]
# class 2 -->[0,0,1]

In [11]:
from keras.utils import to_categorical

In [12]:
y = to_categorical(y)

In [13]:
y.shape

(150, 3)

In [14]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.333,random_state=42)

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)

MinMaxScaler()

In [20]:
scaled_X_train = scaler_object.transform(X_train)

In [21]:
scaled_X_test = scaler_object.transform(X_test)

In [22]:
from keras.models import Sequential

In [23]:
from keras.layers import Dense

In [24]:
model = Sequential()
model.add(Dense(8,input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3,activation='softmax')) #[0.2,0.3,0.5]

In [25]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.fit(scaled_X_train,y_train,epochs=1550,verbose=2)

Epoch 1/1550
4/4 - 0s - loss: 0.0737 - accuracy: 0.9600
Epoch 2/1550
4/4 - 0s - loss: 0.0722 - accuracy: 0.9600
Epoch 3/1550
4/4 - 0s - loss: 0.0732 - accuracy: 0.9700
Epoch 4/1550
4/4 - 0s - loss: 0.0746 - accuracy: 0.9700
Epoch 5/1550
4/4 - 0s - loss: 0.0756 - accuracy: 0.9700
Epoch 6/1550
4/4 - 0s - loss: 0.0748 - accuracy: 0.9700
Epoch 7/1550
4/4 - 0s - loss: 0.0763 - accuracy: 0.9800
Epoch 8/1550
4/4 - 0s - loss: 0.0760 - accuracy: 0.9700
Epoch 9/1550
4/4 - 0s - loss: 0.0751 - accuracy: 0.9700
Epoch 10/1550
4/4 - 0s - loss: 0.0736 - accuracy: 0.9700
Epoch 11/1550
4/4 - 0s - loss: 0.0727 - accuracy: 0.9700
Epoch 12/1550
4/4 - 0s - loss: 0.0718 - accuracy: 0.9600
Epoch 13/1550
4/4 - 0s - loss: 0.0720 - accuracy: 0.9600
Epoch 14/1550
4/4 - 0s - loss: 0.0729 - accuracy: 0.9600
Epoch 15/1550
4/4 - 0s - loss: 0.0728 - accuracy: 0.9600
Epoch 16/1550
4/4 - 0s - loss: 0.0722 - accuracy: 0.9600
Epoch 17/1550
4/4 - 0s - loss: 0.0720 - accuracy: 0.9600
Epoch 18/1550
4/4 - 0s - loss: 0.0723 - 

Epoch 145/1550
4/4 - 0s - loss: 0.0678 - accuracy: 0.9600
Epoch 146/1550
4/4 - 0s - loss: 0.0675 - accuracy: 0.9600
Epoch 147/1550
4/4 - 0s - loss: 0.0675 - accuracy: 0.9600
Epoch 148/1550
4/4 - 0s - loss: 0.0674 - accuracy: 0.9600
Epoch 149/1550
4/4 - 0s - loss: 0.0672 - accuracy: 0.9600
Epoch 150/1550
4/4 - 0s - loss: 0.0672 - accuracy: 0.9600
Epoch 151/1550
4/4 - 0s - loss: 0.0673 - accuracy: 0.9600
Epoch 152/1550
4/4 - 0s - loss: 0.0671 - accuracy: 0.9600
Epoch 153/1550
4/4 - 0s - loss: 0.0675 - accuracy: 0.9600
Epoch 154/1550
4/4 - 0s - loss: 0.0694 - accuracy: 0.9600
Epoch 155/1550
4/4 - 0s - loss: 0.0693 - accuracy: 0.9700
Epoch 156/1550
4/4 - 0s - loss: 0.0693 - accuracy: 0.9700
Epoch 157/1550
4/4 - 0s - loss: 0.0676 - accuracy: 0.9600
Epoch 158/1550
4/4 - 0s - loss: 0.0675 - accuracy: 0.9600
Epoch 159/1550
4/4 - 0s - loss: 0.0670 - accuracy: 0.9600
Epoch 160/1550
4/4 - 0s - loss: 0.0667 - accuracy: 0.9600
Epoch 161/1550
4/4 - 0s - loss: 0.0672 - accuracy: 0.9600
Epoch 162/1550

Epoch 287/1550
4/4 - 0s - loss: 0.0634 - accuracy: 0.9600
Epoch 288/1550
4/4 - 0s - loss: 0.0637 - accuracy: 0.9700
Epoch 289/1550
4/4 - 0s - loss: 0.0642 - accuracy: 0.9700
Epoch 290/1550
4/4 - 0s - loss: 0.0643 - accuracy: 0.9700
Epoch 291/1550
4/4 - 0s - loss: 0.0641 - accuracy: 0.9700
Epoch 292/1550
4/4 - 0s - loss: 0.0641 - accuracy: 0.9700
Epoch 293/1550
4/4 - 0s - loss: 0.0635 - accuracy: 0.9700
Epoch 294/1550
4/4 - 0s - loss: 0.0633 - accuracy: 0.9700
Epoch 295/1550
4/4 - 0s - loss: 0.0635 - accuracy: 0.9600
Epoch 296/1550
4/4 - 0s - loss: 0.0634 - accuracy: 0.9600
Epoch 297/1550
4/4 - 0s - loss: 0.0634 - accuracy: 0.9700
Epoch 298/1550
4/4 - 0s - loss: 0.0635 - accuracy: 0.9700
Epoch 299/1550
4/4 - 0s - loss: 0.0635 - accuracy: 0.9700
Epoch 300/1550
4/4 - 0s - loss: 0.0643 - accuracy: 0.9700
Epoch 301/1550
4/4 - 0s - loss: 0.0643 - accuracy: 0.9700
Epoch 302/1550
4/4 - 0s - loss: 0.0638 - accuracy: 0.9700
Epoch 303/1550
4/4 - 0s - loss: 0.0635 - accuracy: 0.9700
Epoch 304/1550

Epoch 429/1550
4/4 - 0s - loss: 0.0607 - accuracy: 0.9600
Epoch 430/1550
4/4 - 0s - loss: 0.0608 - accuracy: 0.9600
Epoch 431/1550
4/4 - 0s - loss: 0.0607 - accuracy: 0.9600
Epoch 432/1550
4/4 - 0s - loss: 0.0608 - accuracy: 0.9600
Epoch 433/1550
4/4 - 0s - loss: 0.0605 - accuracy: 0.9600
Epoch 434/1550
4/4 - 0s - loss: 0.0605 - accuracy: 0.9700
Epoch 435/1550
4/4 - 0s - loss: 0.0601 - accuracy: 0.9700
Epoch 436/1550
4/4 - 0s - loss: 0.0605 - accuracy: 0.9700
Epoch 437/1550
4/4 - 0s - loss: 0.0606 - accuracy: 0.9700
Epoch 438/1550
4/4 - 0s - loss: 0.0607 - accuracy: 0.9700
Epoch 439/1550
4/4 - 0s - loss: 0.0607 - accuracy: 0.9700
Epoch 440/1550
4/4 - 0s - loss: 0.0607 - accuracy: 0.9700
Epoch 441/1550
4/4 - 0s - loss: 0.0605 - accuracy: 0.9700
Epoch 442/1550
4/4 - 0s - loss: 0.0604 - accuracy: 0.9700
Epoch 443/1550
4/4 - 0s - loss: 0.0603 - accuracy: 0.9700
Epoch 444/1550
4/4 - 0s - loss: 0.0601 - accuracy: 0.9700
Epoch 445/1550
4/4 - 0s - loss: 0.0602 - accuracy: 0.9700
Epoch 446/1550

Epoch 571/1550
4/4 - 0s - loss: 0.0599 - accuracy: 0.9700
Epoch 572/1550
4/4 - 0s - loss: 0.0580 - accuracy: 0.9700
Epoch 573/1550
4/4 - 0s - loss: 0.0578 - accuracy: 0.9700
Epoch 574/1550
4/4 - 0s - loss: 0.0577 - accuracy: 0.9700
Epoch 575/1550
4/4 - 0s - loss: 0.0579 - accuracy: 0.9700
Epoch 576/1550
4/4 - 0s - loss: 0.0584 - accuracy: 0.9700
Epoch 577/1550
4/4 - 0s - loss: 0.0581 - accuracy: 0.9700
Epoch 578/1550
4/4 - 0s - loss: 0.0585 - accuracy: 0.9700
Epoch 579/1550
4/4 - 0s - loss: 0.0586 - accuracy: 0.9700
Epoch 580/1550
4/4 - 0s - loss: 0.0585 - accuracy: 0.9800
Epoch 581/1550
4/4 - 0s - loss: 0.0586 - accuracy: 0.9800
Epoch 582/1550
4/4 - 0s - loss: 0.0582 - accuracy: 0.9800
Epoch 583/1550
4/4 - 0s - loss: 0.0581 - accuracy: 0.9700
Epoch 584/1550
4/4 - 0s - loss: 0.0574 - accuracy: 0.9700
Epoch 585/1550
4/4 - 0s - loss: 0.0577 - accuracy: 0.9700
Epoch 586/1550
4/4 - 0s - loss: 0.0578 - accuracy: 0.9700
Epoch 587/1550
4/4 - 0s - loss: 0.0579 - accuracy: 0.9700
Epoch 588/1550

Epoch 713/1550
4/4 - 0s - loss: 0.0590 - accuracy: 0.9700
Epoch 714/1550
4/4 - 0s - loss: 0.0597 - accuracy: 0.9700
Epoch 715/1550
4/4 - 0s - loss: 0.0599 - accuracy: 0.9700
Epoch 716/1550
4/4 - 0s - loss: 0.0599 - accuracy: 0.9700
Epoch 717/1550
4/4 - 0s - loss: 0.0601 - accuracy: 0.9700
Epoch 718/1550
4/4 - 0s - loss: 0.0618 - accuracy: 0.9700
Epoch 719/1550
4/4 - 0s - loss: 0.0625 - accuracy: 0.9700
Epoch 720/1550
4/4 - 0s - loss: 0.0616 - accuracy: 0.9700
Epoch 721/1550
4/4 - 0s - loss: 0.0607 - accuracy: 0.9700
Epoch 722/1550
4/4 - 0s - loss: 0.0588 - accuracy: 0.9700
Epoch 723/1550
4/4 - 0s - loss: 0.0593 - accuracy: 0.9700
Epoch 724/1550
4/4 - 0s - loss: 0.0579 - accuracy: 0.9700
Epoch 725/1550
4/4 - 0s - loss: 0.0567 - accuracy: 0.9600
Epoch 726/1550
4/4 - 0s - loss: 0.0553 - accuracy: 0.9700
Epoch 727/1550
4/4 - 0s - loss: 0.0556 - accuracy: 0.9700
Epoch 728/1550
4/4 - 0s - loss: 0.0557 - accuracy: 0.9700
Epoch 729/1550
4/4 - 0s - loss: 0.0558 - accuracy: 0.9800
Epoch 730/1550

Epoch 855/1550
4/4 - 0s - loss: 0.0566 - accuracy: 0.9700
Epoch 856/1550
4/4 - 0s - loss: 0.0582 - accuracy: 0.9700
Epoch 857/1550
4/4 - 0s - loss: 0.0566 - accuracy: 0.9700
Epoch 858/1550
4/4 - 0s - loss: 0.0542 - accuracy: 0.9700
Epoch 859/1550
4/4 - 0s - loss: 0.0545 - accuracy: 0.9700
Epoch 860/1550
4/4 - 0s - loss: 0.0539 - accuracy: 0.9700
Epoch 861/1550
4/4 - 0s - loss: 0.0547 - accuracy: 0.9800
Epoch 862/1550
4/4 - 0s - loss: 0.0543 - accuracy: 0.9800
Epoch 863/1550
4/4 - 0s - loss: 0.0542 - accuracy: 0.9700
Epoch 864/1550
4/4 - 0s - loss: 0.0542 - accuracy: 0.9700
Epoch 865/1550
4/4 - 0s - loss: 0.0538 - accuracy: 0.9700
Epoch 866/1550
4/4 - 0s - loss: 0.0538 - accuracy: 0.9700
Epoch 867/1550
4/4 - 0s - loss: 0.0540 - accuracy: 0.9700
Epoch 868/1550
4/4 - 0s - loss: 0.0539 - accuracy: 0.9700
Epoch 869/1550
4/4 - 0s - loss: 0.0541 - accuracy: 0.9800
Epoch 870/1550
4/4 - 0s - loss: 0.0530 - accuracy: 0.9700
Epoch 871/1550
4/4 - 0s - loss: 0.0539 - accuracy: 0.9800
Epoch 872/1550

Epoch 997/1550
4/4 - 0s - loss: 0.0527 - accuracy: 0.9800
Epoch 998/1550
4/4 - 0s - loss: 0.0526 - accuracy: 0.9700
Epoch 999/1550
4/4 - 0s - loss: 0.0524 - accuracy: 0.9700
Epoch 1000/1550
4/4 - 0s - loss: 0.0523 - accuracy: 0.9700
Epoch 1001/1550
4/4 - 0s - loss: 0.0523 - accuracy: 0.9700
Epoch 1002/1550
4/4 - 0s - loss: 0.0523 - accuracy: 0.9700
Epoch 1003/1550
4/4 - 0s - loss: 0.0524 - accuracy: 0.9700
Epoch 1004/1550
4/4 - 0s - loss: 0.0524 - accuracy: 0.9700
Epoch 1005/1550
4/4 - 0s - loss: 0.0524 - accuracy: 0.9700
Epoch 1006/1550
4/4 - 0s - loss: 0.0525 - accuracy: 0.9700
Epoch 1007/1550
4/4 - 0s - loss: 0.0526 - accuracy: 0.9800
Epoch 1008/1550
4/4 - 0s - loss: 0.0527 - accuracy: 0.9800
Epoch 1009/1550
4/4 - 0s - loss: 0.0526 - accuracy: 0.9800
Epoch 1010/1550
4/4 - 0s - loss: 0.0524 - accuracy: 0.9800
Epoch 1011/1550
4/4 - 0s - loss: 0.0524 - accuracy: 0.9800
Epoch 1012/1550
4/4 - 0s - loss: 0.0525 - accuracy: 0.9800
Epoch 1013/1550
4/4 - 0s - loss: 0.0525 - accuracy: 0.9800


Epoch 1136/1550
4/4 - 0s - loss: 0.0511 - accuracy: 0.9800
Epoch 1137/1550
4/4 - 0s - loss: 0.0513 - accuracy: 0.9800
Epoch 1138/1550
4/4 - 0s - loss: 0.0516 - accuracy: 0.9800
Epoch 1139/1550
4/4 - 0s - loss: 0.0521 - accuracy: 0.9800
Epoch 1140/1550
4/4 - 0s - loss: 0.0523 - accuracy: 0.9800
Epoch 1141/1550
4/4 - 0s - loss: 0.0522 - accuracy: 0.9800
Epoch 1142/1550
4/4 - 0s - loss: 0.0518 - accuracy: 0.9800
Epoch 1143/1550
4/4 - 0s - loss: 0.0529 - accuracy: 0.9700
Epoch 1144/1550
4/4 - 0s - loss: 0.0512 - accuracy: 0.9800
Epoch 1145/1550
4/4 - 0s - loss: 0.0513 - accuracy: 0.9800
Epoch 1146/1550
4/4 - 0s - loss: 0.0520 - accuracy: 0.9800
Epoch 1147/1550
4/4 - 0s - loss: 0.0508 - accuracy: 0.9800
Epoch 1148/1550
4/4 - 0s - loss: 0.0501 - accuracy: 0.9800
Epoch 1149/1550
4/4 - 0s - loss: 0.0508 - accuracy: 0.9800
Epoch 1150/1550
4/4 - 0s - loss: 0.0515 - accuracy: 0.9800
Epoch 1151/1550
4/4 - 0s - loss: 0.0522 - accuracy: 0.9800
Epoch 1152/1550
4/4 - 0s - loss: 0.0523 - accuracy: 0.98

Epoch 1275/1550
4/4 - 0s - loss: 0.0499 - accuracy: 0.9800
Epoch 1276/1550
4/4 - 0s - loss: 0.0497 - accuracy: 0.9900
Epoch 1277/1550
4/4 - 0s - loss: 0.0505 - accuracy: 0.9800
Epoch 1278/1550
4/4 - 0s - loss: 0.0503 - accuracy: 0.9800
Epoch 1279/1550
4/4 - 0s - loss: 0.0504 - accuracy: 0.9800
Epoch 1280/1550
4/4 - 0s - loss: 0.0502 - accuracy: 0.9800
Epoch 1281/1550
4/4 - 0s - loss: 0.0500 - accuracy: 0.9900
Epoch 1282/1550
4/4 - 0s - loss: 0.0497 - accuracy: 0.9800
Epoch 1283/1550
4/4 - 0s - loss: 0.0496 - accuracy: 0.9900
Epoch 1284/1550
4/4 - 0s - loss: 0.0495 - accuracy: 0.9900
Epoch 1285/1550
4/4 - 0s - loss: 0.0494 - accuracy: 0.9800
Epoch 1286/1550
4/4 - 0s - loss: 0.0497 - accuracy: 0.9800
Epoch 1287/1550
4/4 - 0s - loss: 0.0501 - accuracy: 0.9800
Epoch 1288/1550
4/4 - 0s - loss: 0.0507 - accuracy: 0.9800
Epoch 1289/1550
4/4 - 0s - loss: 0.0503 - accuracy: 0.9800
Epoch 1290/1550
4/4 - 0s - loss: 0.0500 - accuracy: 0.9800
Epoch 1291/1550
4/4 - 0s - loss: 0.0497 - accuracy: 0.98

Epoch 1414/1550
4/4 - 0s - loss: 0.0538 - accuracy: 0.9700
Epoch 1415/1550
4/4 - 0s - loss: 0.0536 - accuracy: 0.9700
Epoch 1416/1550
4/4 - 0s - loss: 0.0527 - accuracy: 0.9700
Epoch 1417/1550
4/4 - 0s - loss: 0.0516 - accuracy: 0.9700
Epoch 1418/1550
4/4 - 0s - loss: 0.0503 - accuracy: 0.9800
Epoch 1419/1550
4/4 - 0s - loss: 0.0498 - accuracy: 0.9800
Epoch 1420/1550
4/4 - 0s - loss: 0.0490 - accuracy: 0.9900
Epoch 1421/1550
4/4 - 0s - loss: 0.0483 - accuracy: 0.9900
Epoch 1422/1550
4/4 - 0s - loss: 0.0486 - accuracy: 0.9900
Epoch 1423/1550
4/4 - 0s - loss: 0.0478 - accuracy: 0.9900
Epoch 1424/1550
4/4 - 0s - loss: 0.0514 - accuracy: 0.9800
Epoch 1425/1550
4/4 - 0s - loss: 0.0501 - accuracy: 0.9800
Epoch 1426/1550
4/4 - 0s - loss: 0.0520 - accuracy: 0.9700
Epoch 1427/1550
4/4 - 0s - loss: 0.0516 - accuracy: 0.9700
Epoch 1428/1550
4/4 - 0s - loss: 0.0509 - accuracy: 0.9700
Epoch 1429/1550
4/4 - 0s - loss: 0.0498 - accuracy: 0.9800
Epoch 1430/1550
4/4 - 0s - loss: 0.0488 - accuracy: 0.98

In [38]:
model.predict_classes(scaled_X_test)

C:\Users\smonn\miniconda3\envs\bigdata\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

In [39]:
predictions = model.predict_classes(scaled_X_test)

In [40]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [41]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [42]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]], dtype=int64)

In [45]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [44]:
accuracy_score(y_test.argmax(axis=1),predictions)

0.96

In [46]:
model.save('myfirstmodel.h5')

In [47]:
from keras.models import load_model

In [48]:
new_model = load_model('myfirstmodel.h5')

In [49]:
new_model.predict_classes(scaled_X_test)

C:\Users\smonn\miniconda3\envs\bigdata\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2], dtype=int64)

Text Generation with keras

In [1]:
def read_file(filepath):
    with open(filepath, encoding="utf8") as f:
        str_text = f.read()
    return str_text

In [2]:
print(read_file('coran.txt'))


Le Coran

 
Sourate 1 : AL-FATIHA (PROLOGUE ou OUVERTURE)
7 versets - Pré-Hégire

-----------------------------------------------------------------------------

1. Au nom d'Allah, le Tout Miséricordieux, le Très Miséricordieux.

2. Louange à Allah, Seigneur de l'univers.

3. Le Tout Miséricordieux, le Très Miséricordieux,

4. Maître du Jour de la rétribution.

5. C'est Toi [Seul] que nous adorons, et c'est Toi [Seul] dont nous implorons secours.

6. Guide-nous dans le droit chemin,

7. le chemin de ceux que Tu as comblés de faveurs, non pas de ceux qui ont encouru Ta colère, ni des égarés.

-----------------------------------------------------------------------------

 
Sourate 2 : Al-BAQARAH (LA VACHE)
286 versets - Post-Hégire

-----------------------------------------------------------------------------

Au nom d’Allah, le Tout Miséricordieux, le Très Miséricordieux.

1. Alif, Lam, Mim  .

2. C'est le Livre au sujet duquel il n'y a aucun doute, c'est un guide pour les pieux  .

3. 

In [3]:
import spacy

C:\Users\smonn\miniconda3\envs\deeptrading\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [4]:
nlp = spacy.load("fr_core_news_sm", disable=['parser','tagger','ner'])

In [5]:
nlp.max_length = 50000000

In [6]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [7]:
d = read_file('coran.txt')

In [8]:
tokens = separate_punc(d)

In [9]:
len(tokens)

175136

In [10]:
#50 words --> network predict #26

In [11]:
train_len = 25 + 1

text_sequences = []

for i in range(train_len, len(tokens)):
    seq = tokens[i-train_len:i]
    
    text_sequences.append(seq)

In [12]:
type(text_sequences)

list

In [13]:
' '.join(text_sequences[0])

"le coran sourate 1 al fatiha prologue ou ouverture 7 versets pré-hégire ----------------------------------------------------------------------------- 1 au nom d' allah le tout miséricordieux le très miséricordieux 2 louange"

In [14]:
' '.join(text_sequences[1])

"coran sourate 1 al fatiha prologue ou ouverture 7 versets pré-hégire ----------------------------------------------------------------------------- 1 au nom d' allah le tout miséricordieux le très miséricordieux 2 louange à"

In [15]:
' '.join(text_sequences[2])

"sourate 1 al fatiha prologue ou ouverture 7 versets pré-hégire ----------------------------------------------------------------------------- 1 au nom d' allah le tout miséricordieux le très miséricordieux 2 louange à allah"

In [16]:
 from keras.preprocessing.text import Tokenizer

In [17]:
tokenizer = Tokenizer()

In [18]:
tokenizer.fit_on_texts(text_sequences)

In [19]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [20]:
sequences[0]

[4,
 145,
 169,
 186,
 247,
 9849,
 9848,
 65,
 3000,
 197,
 100,
 246,
 112,
 186,
 39,
 144,
 17,
 7,
 4,
 59,
 67,
 4,
 104,
 67,
 183,
 381]

In [21]:
tokenizer.index_word

{1: 'et',
 2: 'de',
 3: 'les',
 4: 'le',
 5: 'vous',
 6: 'la',
 7: 'allah',
 8: 'qui',
 9: 'est',
 10: 'que',
 11: 'à',
 12: 'il',
 13: 'ils',
 14: 'nous',
 15: "qu'",
 16: 'ne',
 17: "d'",
 18: 'en',
 19: "l'",
 20: 'des',
 21: 'pas',
 22: '“',
 23: 'ce',
 24: '”',
 25: 'un',
 26: 'a',
 27: 'leur',
 28: 'pour',
 29: 'ceux',
 30: "n'",
 31: 'une',
 32: 'lui',
 33: 'dans',
 34: 'seigneur',
 35: 'eux',
 36: 'sur',
 37: "c'",
 38: 'du',
 39: 'au',
 40: 'sont',
 41: "s'",
 42: 'tu',
 43: 'si',
 44: 'ont',
 45: 'se',
 46: 'avons',
 47: 'y',
 48: 'leurs',
 49: 'fait',
 50: 'donc',
 51: 'dit',
 52: 'gens',
 53: 'son',
 54: 'par',
 55: 'alors',
 56: 'mais',
 57: 'je',
 58: 'terre',
 59: 'tout',
 60: 'quand',
 61: 'jour',
 62: 'certes',
 63: 'bien',
 64: 'avec',
 65: 'ou',
 66: 'aux',
 67: 'miséricordieux',
 68: 'comme',
 69: 'puis',
 70: 'ô',
 71: 'votre',
 72: 'sa',
 73: '-vous',
 74: 'entre',
 75: 'châtiment',
 76: 'plus',
 77: 'ainsi',
 78: 'celui',
 79: 'ton',
 80: 'dis',
 81: 'on',
 82: '

In [22]:
for i in sequences[0]:
    print(f"{i} : {tokenizer.index_word[i]}")

4 : le
145 : coran
169 : sourate
186 : 1
247 : al
9849 : fatiha
9848 : prologue
65 : ou
3000 : ouverture
197 : 7
100 : versets
246 : pré-hégire
112 : -----------------------------------------------------------------------------
186 : 1
39 : au
144 : nom
17 : d'
7 : allah
4 : le
59 : tout
67 : miséricordieux
4 : le
104 : très
67 : miséricordieux
183 : 2
381 : louange


In [23]:
tokenizer.word_counts

OrderedDict([('le', 81790),
             ('coran', 3902),
             ('sourate', 3175),
             ('1', 2956),
             ('al', 2267),
             ('fatiha', 6),
             ('prologue', 7),
             ('ou', 11167),
             ('ouverture', 87),
             ('7', 2740),
             ('versets', 6355),
             ('pré-hégire', 2274),
             ('-----------------------------------------------------------------------------',
              5837),
             ('au', 19151),
             ('nom', 3916),
             ("d'", 53863),
             ('allah', 77550),
             ('tout', 12968),
             ('miséricordieux', 10549),
             ('très', 6237),
             ('2', 2989),
             ('louange', 1326),
             ('à', 66066),
             ('seigneur', 24934),
             ('de', 116194),
             ("l'", 45136),
             ('univers', 1508),
             ('3', 3068),
             ('4', 2964),
             ('maître', 728),
             ('du', 19968)

In [24]:
vocabulary_size = len(tokenizer.word_counts)

In [25]:
vocabulary_size


9849

In [26]:
type(sequences)

list

In [27]:
import numpy as np

sequences = np.array(sequences)

sequences

array([[   4,  145,  169, ...,   67,  183,  381],
       [ 145,  169,  186, ...,  183,  381,   11],
       [ 169,  186,  247, ...,  381,   11,    7],
       ...,
       [ 199,   38,  388, ...,   65,   25,  135],
       [  38,  388, 2164, ...,   25,  135, 1078],
       [ 388, 2164, 5271, ...,  135, 1078,   24]])

In [28]:
from keras.utils import to_categorical

In [29]:
X = sequences[:,:-1]

In [30]:
y = sequences[:,-1]

In [31]:
y = to_categorical(y,num_classes=vocabulary_size+1)

In [32]:
seq_len = X.shape[1]

In [33]:
X.shape

(175110, 25)

In [34]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding

In [35]:
def create_model(vocabulary_size,seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size,seq_len,input_length=seq_len))
    model.add(LSTM(50,return_sequences=True))
    model.add(LSTM(50))
    model.add(Dense(50,activation='relu'))
    model.add(Dense(vocabulary_size,activation='softmax'))
    
    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    
    model.summary()
    
    return model

In [36]:
model = create_model(vocabulary_size+1,seq_len)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 25)            246250    
                                                                 
 lstm (LSTM)                 (None, 25, 50)            15200     
                                                                 
 lstm_1 (LSTM)               (None, 50)                20200     
                                                                 
 dense (Dense)               (None, 50)                2550      
                                                                 
 dense_1 (Dense)             (None, 9850)              502350    
                                                                 
Total params: 786,550
Trainable params: 786,550
Non-trainable params: 0
_________________________________________________________________


In [37]:
from pickle import dump,load

In [38]:
model.fit(X[0:30000],y[0:30000],batch_size=128,epochs=300,verbose=2)

Epoch 1/300
235/235 - 7s - loss: 6.7681 - accuracy: 0.0406 - 7s/epoch - 29ms/step
Epoch 2/300
235/235 - 3s - loss: 6.2097 - accuracy: 0.0437 - 3s/epoch - 12ms/step
Epoch 3/300
235/235 - 3s - loss: 6.0781 - accuracy: 0.0438 - 3s/epoch - 12ms/step
Epoch 4/300
235/235 - 3s - loss: 5.8797 - accuracy: 0.0498 - 3s/epoch - 12ms/step
Epoch 5/300
235/235 - 3s - loss: 5.7571 - accuracy: 0.0541 - 3s/epoch - 12ms/step
Epoch 6/300
235/235 - 3s - loss: 5.6624 - accuracy: 0.0612 - 3s/epoch - 12ms/step
Epoch 7/300
235/235 - 3s - loss: 5.5822 - accuracy: 0.0684 - 3s/epoch - 12ms/step
Epoch 8/300
235/235 - 3s - loss: 5.5067 - accuracy: 0.0765 - 3s/epoch - 12ms/step
Epoch 9/300
235/235 - 3s - loss: 5.4201 - accuracy: 0.0872 - 3s/epoch - 12ms/step
Epoch 10/300
235/235 - 3s - loss: 5.3445 - accuracy: 0.0972 - 3s/epoch - 12ms/step
Epoch 11/300
235/235 - 3s - loss: 5.2732 - accuracy: 0.1037 - 3s/epoch - 12ms/step
Epoch 12/300
235/235 - 3s - loss: 5.2031 - accuracy: 0.1103 - 3s/epoch - 12ms/step
Epoch 13/300


Epoch 100/300
235/235 - 6s - loss: 3.1283 - accuracy: 0.2948 - 6s/epoch - 26ms/step
Epoch 101/300
235/235 - 6s - loss: 3.0962 - accuracy: 0.3004 - 6s/epoch - 27ms/step
Epoch 102/300
235/235 - 6s - loss: 3.0676 - accuracy: 0.3072 - 6s/epoch - 27ms/step
Epoch 103/300
235/235 - 6s - loss: 3.0380 - accuracy: 0.3101 - 6s/epoch - 26ms/step
Epoch 104/300
235/235 - 6s - loss: 3.0038 - accuracy: 0.3150 - 6s/epoch - 27ms/step
Epoch 105/300
235/235 - 6s - loss: 2.9813 - accuracy: 0.3187 - 6s/epoch - 27ms/step
Epoch 106/300
235/235 - 6s - loss: 2.9518 - accuracy: 0.3241 - 6s/epoch - 26ms/step
Epoch 107/300
235/235 - 6s - loss: 2.9190 - accuracy: 0.3307 - 6s/epoch - 26ms/step
Epoch 108/300
235/235 - 6s - loss: 2.8931 - accuracy: 0.3348 - 6s/epoch - 27ms/step
Epoch 109/300
235/235 - 6s - loss: 2.8652 - accuracy: 0.3417 - 6s/epoch - 26ms/step
Epoch 110/300
235/235 - 6s - loss: 2.8357 - accuracy: 0.3483 - 6s/epoch - 26ms/step
Epoch 111/300
235/235 - 6s - loss: 2.8174 - accuracy: 0.3520 - 6s/epoch - 26

Epoch 198/300
235/235 - 7s - loss: 1.1777 - accuracy: 0.7022 - 7s/epoch - 29ms/step
Epoch 199/300
235/235 - 7s - loss: 1.1647 - accuracy: 0.7056 - 7s/epoch - 29ms/step
Epoch 200/300
235/235 - 7s - loss: 1.1520 - accuracy: 0.7105 - 7s/epoch - 28ms/step
Epoch 201/300
235/235 - 6s - loss: 1.1460 - accuracy: 0.7104 - 6s/epoch - 26ms/step
Epoch 202/300
235/235 - 6s - loss: 1.1259 - accuracy: 0.7149 - 6s/epoch - 26ms/step
Epoch 203/300
235/235 - 6s - loss: 1.1158 - accuracy: 0.7188 - 6s/epoch - 26ms/step
Epoch 204/300
235/235 - 6s - loss: 1.1003 - accuracy: 0.7218 - 6s/epoch - 26ms/step
Epoch 205/300
235/235 - 6s - loss: 1.0890 - accuracy: 0.7225 - 6s/epoch - 26ms/step
Epoch 206/300
235/235 - 6s - loss: 1.0769 - accuracy: 0.7280 - 6s/epoch - 26ms/step
Epoch 207/300
235/235 - 6s - loss: 1.0555 - accuracy: 0.7321 - 6s/epoch - 27ms/step
Epoch 208/300
235/235 - 6s - loss: 1.0575 - accuracy: 0.7319 - 6s/epoch - 25ms/step
Epoch 209/300
235/235 - 6s - loss: 1.0373 - accuracy: 0.7406 - 6s/epoch - 25

Epoch 296/300
235/235 - 3s - loss: 0.3528 - accuracy: 0.9128 - 3s/epoch - 14ms/step
Epoch 297/300
235/235 - 3s - loss: 0.3405 - accuracy: 0.9157 - 3s/epoch - 14ms/step
Epoch 298/300
235/235 - 3s - loss: 0.3284 - accuracy: 0.9177 - 3s/epoch - 15ms/step
Epoch 299/300
235/235 - 3s - loss: 0.3307 - accuracy: 0.9168 - 3s/epoch - 14ms/step
Epoch 300/300
235/235 - 3s - loss: 0.3331 - accuracy: 0.9172 - 3s/epoch - 13ms/step


In [39]:
model.save('coran_model.h5')

In [40]:
dump(tokenizer,open('my_simpletokenizer','wb'))

In [41]:
from keras_preprocessing.sequence import pad_sequences


In [42]:
def generate_text(model,tokenizer,seq_len,seed_text,num_gen_words):
    
    output_text = []
    
    input_text = seed_text
    
    for i in range(num_gen_words):
        
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        pad_encoded = pad_sequences([encoded_text],maxlen=seq_len,truncating='pre')
    
        pred_word_ind = model.predict(pad_encoded,verbose=0)[0]
 
        classes_x_ind =np.argmax(pred_word_ind)
        
        pred_word = tokenizer.index_word[classes_x_ind]
        
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
    
    return ' '.join(output_text)

In [43]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [44]:
random_seed_text = text_sequences[random_pick]

In [45]:
random_seed_text

['aad',
 'ont',
 'traité',
 'de',
 'menteur',
 'leur',
 'messager',
 'comment',
 'furent',
 'mon',
 'châtiment',
 'et',
 'mes',
 'avertissements',
 '19',
 'nous',
 'avons',
 'envoyé',
 'contre',
 'eux',
 'un',
 'vent',
 'violent',
 'et',
 'glacial',
 'en']

In [46]:
seed_text = ' '.join(random_seed_text)

In [48]:
seed_text = "Par la plume et ce qu'il écrivent"

In [49]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)

"à titre du livre venez par ta famille à qu' avez la piété si vous étiez croyants .et qui prend leur mêmes si vous deux"